CREATE TABLE BOOK
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    ISBN            INTEGER      NOT NULL CHECK (LENGTH(ISBN) IN (10, 13)),
    WRITER          VARCHAR(255) NOT NULL,
    TITLE           VARCHAR(255) NOT NULL,
    PUBLISHING_DATE DATE
);

CREATE TABLE REVIEW
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOK_ISBN     INTEGER NOT NULL,
    REVIEW_DATE   DATE    NOT NULL,
    REVIEW_TEXT   VARCHAR(255),
    REVIEW_RATING INTEGER NOT NULL CHECK (REVIEW_RATING BETWEEN 0 AND 5),

    FOREIGN KEY (BOOK_ISBN) REFERENCES BOOK (ISBN) ON DELETE CASCADE
);



